version: "3.9"

services:
  converter:
    build: ./converter
    container_name: md_converter
    volumes:
      - ./conteudo:/app/conteudo
      - ./html:/app/html
      - ./logs:/app/logs
    restart: always
    user: "${UID}:${GID}" 

  server:
    build: ./server
    container_name: html_server
    ports:
      - "8080:8080"
    volumes:
      - ./html:/app/html
    restart: always
    user: "${UID}:${GID}"
