version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_web_app
    ports:
      - "8000:8000"
    volumes:
      - ./html:/app/html
      - ./:/app
    restart: always
